use_frameworks!
platform :ios, '9.0'

target 'TopRouter_Example' do
  pod 'TopRouter', :path => '../'
  pod 'TPUIKit'
  pod 'Masonry'
  
  target 'TopRouter_Tests' do
    inherit! :search_paths
    
    
  end
end
